#!/usr/bin/env python3

import logging
import gzip
import sys
import unicodedata
import click
import re
import requests
from io import StringIO
from itertools import chain
from collections import defaultdict
from collections.abc import Generator
from dataclasses import dataclass, field
from string import Template
from textwrap import dedent
from os import path
from pathlib import Path
from typing import TypeVar
from rdflib import Graph, RDF, OWL, RDFS, URIRef, Namespace, BNode, Literal, Node, IdentifiedNode
from rdflib.collection import Collection
from rdflib.namespace import split_uri
from rdflib.util import guess_format

type Triple = tuple[Node, Node, Node]

SWRL = Namespace("http://www.w3.org/2003/11/swrl#")
VOAF = Namespace("http://purl.org/vocommons/voaf#")
MOD = Namespace("mod:")

EMPTY_SET = frozenset()


#
# DOWNLOAD
#

def download(output_dir: str = "./extvoc") -> None:
    """
    Download external vocabularies referenced in CRIMA into the directory specified.

    Files that already exist in the output directory are not overridden, and the corresponding vocabularies are not
    downloaded (delete them to force download). Vocabularies are always converted into and saved in Turtle format.

    :param output_dir: the output directory
    """
    # Create output directory (and parent dirs) if needed
    dir = Path(output_dir)
    dir.mkdir(parents=True, exist_ok=True)

    # Helper function that downloads a vocabulary file if missing, asking for 'text/turtle' unless 'format' is given,
    # in which case conversion will occur from that format. If 'ontology_iri' is given, a corresponding triple
    # '<ontology_iri> a owl:Ontology' will be added. Errors are logged and ignored (no file saved).
    def get(filename: str, url: str | None, *, format: str | None = None, ontology_iri: URIRef | None = None):
        file = dir / filename
        try:
            if file.is_file():
                return
            logging.info(f"Processing {filename}: {url}")
            graph = create_graph()
            if url:
                headers = {} if format else {"Accept": "text/turtle"}
                response = requests.get(url, allow_redirects=True, headers=headers)
                response.raise_for_status()
                graph.parse(source=response.content, format=format, publicID=url)
            if ontology_iri or not url:
                graph.add((ontology_iri, RDF.type, OWL.Ontology))
            with file.open("wb") as f:
                graph.serialize(destination=f, format="longturtle")
        except Exception as ex:
            logging.error(f"Could not fetch {url}: {str(ex)}")

    # Download all vocabularies
    get("as.ttl", "https://www.w3.org/ns/activitystreams-owl")
    get("bibo.ttl", "http://purl.org/ontology/bibo/")
    get("cc.ttl", "https://creativecommons.org/schema.rdf", format="xml", ontology_iri=URIRef("http://creativecommons.org/ns#"))
    get("clc.ttl", "http://www.w3.org/2015/03/corine", ontology_iri=URIRef("http://www.w3.org/2015/03/corine"))
    get("dbo.ttl", "https://akswnc7.informatik.uni-leipzig.de/dstreitmatter/archivo/dbpedia.org/ontology--DEV/2024.07.29-001000/ontology--DEV_type=orig.owl", format="xml")
    get("dcat.ttl", "https://www.w3.org/ns/dcat3.ttl")
    get("dcmitype.ttl", "https://www.dublincore.org/specifications/dublin-core/dcmi-terms/dublin_core_type.ttl", ontology_iri=URIRef("http://purl.org/dc/dcmitype/")) # not imported
    get("dcterms.ttl", "https://www.dublincore.org/specifications/dublin-core/dcmi-terms/dublin_core_terms.ttl", ontology_iri=URIRef("http://purl.org/dc/terms/"))
    get("dpo.ttl", "https://raw.githubusercontent.com/KnowWhereGraph/dmdo/refs/heads/main/modules/disaster-properties-module/disaster-properties-ontology.ttl")
    get("dtype.ttl", "https://www.linkedmodel.org/schema/dtype", format="xml")
    get("foaf.ttl", "https://xmlns.com/foaf/spec/index.rdf", format="xml")
    get("geo.ttl", "http://www.opengis.net/ont/geosparql")
    get("org.ttl", "https://www.w3.org/ns/org")
    get("prov.ttl", "https://www.w3.org/ns/prov-o")
    get("qudt.ttl", "https://qudt.org/schema/qudt")
    get("qudt-coords.ttl", "https://qudt.org/schema/coordinateSystems/")
    get("qudt-datatype.ttl", "https://qudt.org/schema/datatype")
    get("qudt-facade.ttl", "https://qudt.org/schema/facade/qudt")
    get("qudt-prefix.ttl", "https://qudt.org/vocab/prefix")
    get("qudt-qkdv.ttl", "https://qudt.org/vocab/dimensionvector")
    get("qudt-quantitykind.ttl", "https://qudt.org/vocab/quantitykind")
    get("qudt-soqk.ttl", "https://qudt.org/vocab/soqk")
    get("qudt-sou.ttl", "http://qudt.org/vocab/sou")
    get("qudt-unit.ttl", "https://qudt.org/vocab/unit/")
    get("qudt-usertest.ttl", None, ontology_iri=URIRef("http://qudt.org/collection/usertest"))
    get("schema.ttl", "https://schema.org/version/latest/schemaorg-current-http.ttl", ontology_iri=URIRef("http://schema.org/"))
    get("skos.ttl", "https://www.w3.org/TR/skos-reference/skos.rdf", format="xml")
    get("sosa.ttl", "https://raw.githubusercontent.com/w3c/sdw-sosa-ssn/refs/heads/gh-pages/ssn/rdf/ontology/core/sosa.ttl") # not imported
    get("sosa-common.ttl", "https://raw.githubusercontent.com/w3c/sdw-sosa-ssn/refs/heads/gh-pages/ssn/rdf/ontology/core/sosa-common.ttl")
    get("sosa-obs.ttl", "https://raw.githubusercontent.com/w3c/sdw-sosa-ssn/refs/heads/gh-pages/ssn/rdf/ontology/core/sosa-observation.ttl")
    get("swrl.ttl", "https://www.w3.org/submissions/2004/SUBM-SWRL-20040521/swrl.rdf", format="xml", ontology_iri=URIRef("http://www.w3.org/2003/11/swrl#")) # not imported
    get("time.ttl", "http://www.w3.org/2006/time")
    get("vaem.ttl", "https://www.linkedmodel.org/schema/vaem", format="xml")
    get("vann.ttl", "https://vocab.org/vann/vann-vocab-20100607.rdf", format="xml")
    get("voaf.ttl", "https://raw.githubusercontent.com/pyvandenbussche/lov/refs/heads/master/vocommons/voaf/v2.3/voaf_v2.3.rdf", format="xml")
    get("wmdr-unit.ttl", "https://codes.wmo.int/wmdr/unit?_format=ttl&_view=with_metadata&status=valid", ontology_iri=URIRef("http://codes.wmo.int/wmdr/unit/"))
    get("xkos.ttl", "http://rdf-vocabulary.ddialliance.org/xkos.ttl")


#
# SANITIZE
#

T = TypeVar("T")

def sanitize(data: T) -> T:

    if isinstance(data, Graph):
        graph = create_graph(namespaces_from=data)
        for s, p, o in data:
            s = sanitize(s)
            p = sanitize(p)
            o = sanitize(o)
            graph.add((s, p, o))
        return graph

    if isinstance(data, URIRef):
        iri = sanitize(str(data))
        return URIRef(iri)

    if isinstance(data, Literal):
        value = sanitize(str(data))
        return Literal(value, lang=data.language, datatype=data.datatype)

    if isinstance(data, str) and not isinstance(data, Node):
        text = unicodedata.normalize("NFKC", data)
        text = SANITIZE_CONTROL_CHARS_REGEX.sub("", data)
        return text.translate(SANITIZE_TRANSLATION_TABLE)

    return data


SANITIZE_CONTROL_CHARS_REGEX = re.compile(r"[\u202D\u200e]+")

SANITIZE_TRANSLATION_TABLE = str.maketrans({
    "\u201c": '"',
    "\u201d": '"',
    "\u2018": "'",
    "\u2019": "'",
    "\u2013": "-",
    "—": "-",
    "\u2212": "-",
    "\u00A0": " ",
    "\uFFFC": " "
})


#
# SPLIT
#

@dataclass(frozen=True)
class Module:
    iri: URIRef
    serialization: str = field(compare=False)
    defines_namespaces_tbox: set[str] = field(compare=False)
    defines_namespaces_abox: set[str] = field(compare=False)
    includes_subjects_of: set[URIRef] = field(compare=False)
    includes_objects_of: set[URIRef] = field(compare=False)
    includes_statements_with: set[set[URIRef]] = field(compare=False)
    uses: set[URIRef] = field(compare=False)


@dataclass(frozen=True)
class IRITerm:
    iri: URIRef
    defined_by: set[Module]
    included_by: set[Module]


def split(graph: Graph, leftover: Graph | None = None) -> dict[str, Graph]:
    modules = extract_modules(graph)
    terms = extract_terms(graph, modules)
    return allocate_triples(graph, modules, terms, leftover)


def extract_modules(graph: Graph) -> dict[URIRef, Module]:

    iris: set[URIRef] = set(graph.subjects(RDF.type, OWL.Ontology))
    if any(not isinstance(n, URIRef) for n in iris):
        raise ValueError(f"Expected IRI as module identifier, got a BNode: check subjects of {MOD.hasSerialization}")

    return {
        iri: Module(
            iri = iri,
            serialization = graph.value(iri, MOD.hasSerialization),
            defines_namespaces_tbox = {str(o) for p in (MOD.definesNamespace, MOD.definesNamespaceTBox) for o in graph.objects(iri, p)},
            defines_namespaces_abox = {str(o) for p in (MOD.definesNamespace, MOD.definesNamespaceABox) for o in graph.objects(iri, p)},
            includes_subjects_of = {p for p in graph.objects(iri, MOD.includesSubjectsOf) if isinstance(p, URIRef)},
            includes_objects_of = {p for p in graph.objects(iri, MOD.includesObjectsOf) if isinstance(p, URIRef)},
            includes_statements_with = {frozenset(Collection(graph, o)) for o in graph.objects(iri, MOD.includesStatementsWith)},
            uses =
                {o for o in graph.subjects(iri, VOAF.usedBy) if o in iris} |
                {o  for p in (VOAF.reliesOn, VOAF.extends, VOAF.metadataVoc, VOAF.specializes,
                              VOAF.generalizes, VOAF.hasEquivalencesWith, VOAF.hasDisjunctionsWith)
                    for o in graph.objects(iri, p)
                    if o in iris}
        )
        for iri in iris
    }


def extract_terms(graph: Graph, modules: dict[URIRef, Module]) -> dict[URIRef, IRITerm]:

    tbox_terms = set(graph.predicates())
    for t in (RDF.Property, OWL.DatatypeProperty, OWL.ObjectProperty, OWL.AnnotationProperty, OWL.FunctionalProperty,
              OWL.SymmetricProperty, OWL.AsymmetricProperty, OWL.ReflexiveProperty, OWL.IrreflexiveProperty, OWL.TransitiveProperty,
              RDFS.Class, OWL.Class, RDFS.Datatype, OWL.Restriction, OWL.Ontology):
        tbox_terms.update(s for s in graph.subjects(RDF.type, t) if isinstance(s, URIRef))
    for p in (RDFS.subClassOf, RDFS.subPropertyOf, OWL.inverseOf):
        tbox_terms.update(s for s in graph.subjects(predicate=p) if isinstance(s, URIRef))
    for p in (RDFS.subClassOf, RDFS.subPropertyOf, OWL.inverseOf, OWL.allValuesFrom, OWL.someValuesFrom):
        tbox_terms.update(o for o in graph.objects(predicate=p) if isinstance(o, URIRef))

    module_index: dict[tuple[bool, str], set[Module]] = {}
    for isabox in (False, True):
        for m in modules.values():
            for ns in (m.defines_namespaces_abox if isabox else m.defines_namespaces_tbox):
                module_index.setdefault((isabox, ns), set()).add(m)

    allocation: dict[URIRef, IRITerm] = {}

    for t in {t for triple in graph for t in triple if isinstance(t, URIRef)}:
        isabox = t not in tbox_terms
        try:
            ns = split_uri(t)[0]
        except:
            ns = str(t)
        if ns not in SPLIT_IGNORED_NAMESPACES:
            defined_by = frozenset(module_index.get((isabox, ns), EMPTY_SET))
            allocation[t] = IRITerm(iri=t, defined_by=defined_by, included_by=defined_by)

    for s, o in chain(
        ((s, o) for s, _, o in graph.triples((None, RDFS.isDefinedBy, None))),
        ((o, s) for s, _, o in graph.triples((None, MOD.definesTerm, None))),
    ):
        m = modules.get(o)
        term = allocation.get(s)
        if m and term and m not in term.defined_by:
            defined_by = frozenset({m, *term.defined_by})
            allocation[s] = IRITerm(iri=s, defined_by=defined_by, included_by=defined_by)

    # Assign Ontology IRIs exclusively to themselves, overriding prior allocations
    for m in modules.values():
        defined_by = frozenset({m})
        allocation[m.iri] = IRITerm(iri=m.iri, defined_by=defined_by, included_by=defined_by)

    for m in modules.values():
        pairs = \
            {(s, o) for p in m.includes_objects_of for s, _, o in graph.triples((None, p, None)) if isinstance(o, IdentifiedNode)} | \
            {(s, o) for p in m.includes_subjects_of for o, _, s in graph.triples((None, p, None)) if isinstance(s, IdentifiedNode)}
        bnodes: set[BNode] = set()
        fixpoint = False
        while not fixpoint:
            fixpoint = True
            for s, o in pairs:
                s_term = allocation.get(s)
                if s_term and m in s_term.included_by or s in bnodes:
                    if isinstance(o, BNode):
                        if o not in bnodes:
                            bnodes.add(o)
                            fixpoint = False
                    else:
                        o_term = allocation.get(o)
                        if o_term and m not in o_term.included_by:
                            included_by = frozenset({m, *o_term.included_by})
                            allocation[o] = IRITerm(iri=o, defined_by=o_term.defined_by, included_by=included_by)
                            fixpoint = False

    return allocation


def chunk_triples(graph: Graph) -> Generator[list[Triple], None, None]:
    """
    Split an RDF graph into minimal chunks so that all triples for a BNode are in the same chunk.

    The rationale is that BNodes have local scope and their triples cannot be split across files, hence they must be
    allocated to the same Ontology file. If there are no BNodes, returned chunks consist just of one triple.

    :param graph: the RDF graph whose triples have to be chunked
    :return: a generator that returns chunks as they are identified, each chunk being a non-empty list of triples
    """
    # Allocate a set to track BNodes visited so far, as they cannot be returned in following chunks
    visited_bnodes = set()

    # Recursive helper function that fetches all triples of BNode and of all other BNodes linked to it, adding these
    # triples to the passed 'chunk' list. Return False (with no triple added) if BNode was already visited.
    def visit(node: BNode, chunk: list[Triple]) -> bool:
        if node in visited_bnodes:
            return False
        visited_bnodes.add(node)
        for _, p, o in graph.triples((node, None, None)):
            if not isinstance(o, BNode) or not visit(o, chunk):
                chunk.append((node, p, o))
        for s, p, _ in graph.triples((None, None, node)):
            if not isinstance(s, BNode) or not visit(s, chunk):
                chunk.append((s, p, node))

    # Scans the graph one triple at a time, visiting encountered BNodes, and returning all non empty chunks
    for s, p, o in graph:
        chunk = []
        if isinstance(s, BNode):
            visit(s, chunk)
        elif isinstance(o, BNode):
            visit(o, chunk)
        else:
            chunk.append((s, p, o))
        if len(chunk) > 0:
            yield chunk


def allocate_triples(graph: Graph, modules: dict[URIRef, Module], terms: dict[URIRef, IRITerm], leftover: Graph | None = None) -> dict[str, Graph]:

    postponed_chunks: dict[Node, list[Triple]] = {}

    def postpone(chunk: list[Triple]) -> bool:
        if len(chunk) == 1:
            s, p, o = chunk[0]
            if p == RDF.type and o == SWRL.Variable:
                postponed_chunks[s] = chunk
                return True
        return False

    module_deps = {m: {modules[u] for u in m.uses} for m in modules.values()}

    module_stmt_iris_idx: dict[URIRef, set[Module]] = defaultdict(set)
    for m in modules.values():
        for stmt_iris in m.includes_statements_with:
            for iri in stmt_iris:
                module_stmt_iris_idx[iri].add(m)

    module_graphs = {
        m.serialization: create_graph(namespaces_from=graph)
        for m in modules.values() if m.serialization
    }

    for chunk in chunk_triples(graph):

        emitted = False

        chunk_terms_iris = {t for triple in chunk for t in triple if isinstance(t, URIRef)}
        chunk_terms = {terms[iri] for iri in chunk_terms_iris if iri in terms}

        candidate_modules_base: set[Module] = {
            m
            for s, p, o in chunk
            for t in ((s, o) if p != RDF.type else (s,))
            for m in (terms[t].included_by if t in terms else EMPTY_SET)
            if m.serialization
        }

        candidate_modules_extra: set[Module] = {m for iri in chunk_terms_iris for m in module_stmt_iris_idx.get(iri, EMPTY_SET)}

        candidate_modules = candidate_modules_base | candidate_modules_extra

        for m in candidate_modules:

            m_deps = module_deps[m]
            emit_to_m = \
                m in candidate_modules_base and \
                all(m in t.included_by or not m_deps.isdisjoint(t.defined_by) for t in chunk_terms)

            if not emit_to_m:
                for stmt_iris in m.includes_statements_with:
                    if stmt_iris.issubset(chunk_terms_iris) and all(
                        m in t.included_by or not m_deps.isdisjoint(t.defined_by)
                        for t in chunk_terms
                        if t.iri not in stmt_iris
                    ):
                        emit_to_m = True
                        continue

            if emit_to_m:
                emitted = True
                mg = module_graphs[m.serialization]
                for triple in chunk:
                    mg.add(triple)

        if not emitted:
            if not postpone(chunk) and leftover is not None:
                for triple in chunk:
                    leftover.add(triple)

    if postponed_chunks:
        module_nodes = {k: {n for triple in g for n in triple} for k, g in module_graphs.items()}
        for node, chunk in postponed_chunks.items():
            emitted = False
            for k, nodes in module_nodes.items():
                if node in nodes:
                    emitted = True
                    g = module_graphs[k]
                    for triple in chunk:
                        g.add(triple)
            if not emitted and leftover is not None:
                for triple in chunk:
                    leftover.add(triple)

    return module_graphs


SPLIT_IGNORED_NAMESPACES = {
    "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "http://www.w3.org/2000/01/rdf-schema#",
    "http://www.w3.org/2002/07/owl#",
    "http://www.w3.org/2001/XMLSchema#",
    "http://www.w3.org/2003/11/swrl#",
    "urn:swrl:var#"
}


#
# MERMAID
#

def mermaid(graph: Graph, extra_content: tuple[str, ...] = ()) -> str:

    @dataclass(frozen=True)
    class Subgraph:
        id: str
        label: str

    @dataclass(frozen=True)
    class Node:
        id: str
        label: str
        iri: URIRef
        subgraph: Subgraph | None

    node_index = {}
    for iri, _, serialization in graph.triples((None, MOD.hasSerialization, None)):
        parts = str(serialization).rsplit("/", 1)
        s = Subgraph("sg_main", " ") if len(parts) == 1 else Subgraph(id="sg_" + re.sub(r"[^a-zA-Z]", "_", parts[0]), label=parts[0])
        node_label = parts[-1].split(".", 1)[0]
        node_index[iri] = Node(id=re.sub(r"[^a-zA-Z]", "_", node_label), label=node_label, iri=iri, subgraph=s)

    nodes = sorted([n for n in node_index.values()], key=lambda n: n.id)
    subgraphs = sorted({n.subgraph for n in node_index.values() if n.subgraph}, key=lambda s: s.id)

    props = (VOAF.reliesOn, VOAF.extends, VOAF.metadataVoc, VOAF.specializes, VOAF.generalizes,
             VOAF.hasEquivalencesWith, VOAF.hasDisjunctionsWith)
    parents = {n.iri: set(o for p in props for o in graph.objects(n.iri, p) if o in node_index and o != n.iri) for n in nodes}
    for n, n_parents in parents.items():
        n_parents -= {p2 for p1 in n_parents for p2 in parents[p1]}

    buffer = StringIO()
    buffer.write(dedent("""\
        ```mermaid
        flowchart BT
            classDef invisible fill:transparent,stroke:transparent;
            classDef subvoc fill:#7588a3,stroke:#555555,stroke-width:1px;
            classDef voc fill:#7588a3,stroke:#555555,stroke-width:2px;\n"""))
    for s in subgraphs:
        buffer.write(f"    style {s.id} fill:transparent,stroke:#7588a3,stroke-width:3px;\n")
    buffer.write("\n")

    for s in subgraphs:
        buffer.write(f"    subgraph {s.id}[\"<b>{s.label}</b>\"]\n")
        for n in (n for n in nodes if n.subgraph == s):
            buffer.write(f"        {n.id}[\"<b>{n.label}</b>\"]:::subvoc\n")
        buffer.write(f"    end\n\n")

    for n in (n for n in nodes if n.subgraph is None):
        buffer.write(f"    {n.id}[\"<b>{n.label}</b>\"]:::voc\n")
    buffer.write("\n")

    if extra_content:
        for line in extra_content:
            buffer.write(f"    {line}\n")
        buffer.write("\n")

    for n, n_parents in parents.items():
        for p in sorted(n_parents):
            buffer.write(f"    {node_index[n].id} --> {node_index[p].id}\n")
    buffer.write("\n")

    for n in nodes:
        buffer.write(f"    click {n.id} href \"{n.iri}\"\n")

    buffer.write("```\n")

    return buffer.getvalue()


#
# HELPER FUNCTIONS
#

def create_graph(*, namespaces_from: Graph | None = None) -> Graph:
    """
    Create an RDF graph, optionally copying <prefix, namespace> bindings from a supplied graph.

    :param namespaces_from: the optional graph to copy <prefix, namespace> bindings from
    :return the created RDF graph
    """
    graph = Graph(bind_namespaces="core")
    if namespaces_from is not None:
        for prefix, namespace in namespaces_from.namespaces():
            graph.bind(prefix, namespace)
    return graph


def rdf_read(graph: Graph, path: str) -> None:
    """
    Read the RDF file at the path specified ('-' for stdin, '.ext:' prefix to override format) into a RDF graph.

    :param graph: the RDF graph where to add parsed triples and <prefix, namespace> bindings
    :param path: the file path or '-' for stdin, optionally prepended with '.ext:' to override detected RDF format
    """
    tokens = path.split(":")
    path = tokens[-1]
    if path.endswith((".xml", ".xml.gz")) and len(tokens) == 1:
        raise ValueError("Refusing to parse .xml files: use .rdf extension, or force RDF/XML parsing via .xml: prefix")
    fmt = guess_format(path if len(tokens) == 1 else "dummy" + tokens[0])
    f = sys.stdin.buffer if path == "-" else \
        gzip.open(path, "rb") if path.endswith(".gz") else \
        open(path, "rb")
    with f:
        graph.parse(source=f, format=fmt)


def rdf_write(graph: Graph, path: str) -> None:
    """
    Write an RDF graph to the file at the path specified ('-' for stdout, '.ext:' prefix to override format).

    :param graph: the RDF graph whose triples and <prefix, namespace> bindings are to be written to file
    :param path: the file path or '-' for stdout, optionally prepended with '.ext:' to override detected RDF format
    """
    tokens = path.split(":")
    path = tokens[-1]
    fmt = guess_format(path if len(tokens) == 1 else "dummy" + tokens[0])
    opts = {"encoding": "utf-8"} if fmt in ("nt", "ntriples") else {}
    f = sys.stdout.buffer if path == "-" else \
        gzip.open(path, "wb") if path.endswith(".gz") else \
        open(path, "wb")
    with f:
        graph.serialize(destination=f, format=fmt, canon=True, **opts)


#
# CLI INTERFACE
#

@click.group(context_settings={"show_default": True, "max_content_width": 120})
@click.option("-v", "--verbose", is_flag=True, help="log debug information to stderr")
def _cli(verbose: bool = False) -> None:
    """
    Helper script to manage CRIMA ontology.
    """
    logging.basicConfig(format="%(asctime)s (%(levelname).1s) %(message)s", datefmt="%H:%M:%S")
    logging.getLogger().setLevel(logging.DEBUG if verbose else logging.INFO)


@_cli.command(name="download")
@click.option("-o", "--output-dir", default="./extvoc", metavar="DIR",
              help="directory where to download external vocabularies (default: './extvoc')")
def _cli_download(output_dir: str = './extvoc') -> None:
    """
    Download external vocabularies referenced by the CRIMA ontology.

    Vocabularies are downloaded in Turtle format, performing conversion to Turtle if necessary. For compatibility with
    Protégé, an additional triple '<vocabulary_iri> a owl:Ontology' is stored in case the downloaded vocabulary does
    not already contain it. A vocabulary is not downloaded if the corresponding file is already present in the target
    directory (delete it to force download). Parsing and serializing via rdflib is always performed even if data
    already comes in Turtle, to both handle relative IRIs (replaced as full IRIs in saved file) and provide a
    consistent output that facilitates finding differences.
    """
    download(output_dir)


@_cli.command(name="sanitize")
@click.argument("input_files", metavar="INPUT_FILE...", nargs=-1)
@click.option("-o", "--output-file", default=".ttl:-", help="output text file ('-' for stdout, the default)")
@click.option("-p", "--prefixes-from", help="optionally reuse prefixes from supplied file")
def _cli_sanitize(input_files: list[str], output_file: str = '.ttl:-', prefixes_from: str | None = None) -> None:
    """
    Sanitize RDF data from one or more files, writing sanitized RDF output to a specified file.

    File option/arguments allow the use of '-' to denote stdin/stdout, and an optional prefix '.ext:' to force a
    specific RDF format (e.g., '.ttl:path_to_rdf_file). Read from stdin if no input file is specified.
    """
    graph = create_graph()
    for input_file in input_files or [".ttl:-"]:
        rdf_read(graph, input_file)

    if prefixes_from:
        graph.namespace_manager.reset()
        rdf_read(graph, prefixes_from)

    graph = sanitize(graph)

    builtin_datatype_namespaces = {
        "http://www.w3.org/2001/XMLSchema#" ,
        "http://www.w3.org/1999/02/22-rdf-syntax-ns#" ,
        "http://www.w3.org/2000/01/rdf-schema#" ,
        "http://www.w3.org/2002/07/owl#"
    }

    for s in list(graph.subjects(RDF.type, RDFS.Datatype)):
        if isinstance(s, URIRef):
            ns = split_uri(s)[0]
            if ns in builtin_datatype_namespaces:
                graph.remove((s, RDF.type, RDFS.Datatype))

    rdf_write(graph, output_file)


@_cli.command(name="merge")
@click.argument("inputs", metavar="INPUT_FILE...", nargs=-1)
@click.option("-o", "--output-file", default="-", help="output merged file ('-' for stdout, the default)")
@click.option("-l", "--languages", multiple=True, help="the rdf:langString languages to preserve in the merged file (e.g., 'en,it,de')")
@click.option("-s", "--simplify", is_flag=True, help="remove owl:imports statements")
def _cli_merge(inputs: list[str], output_file: str = "-", languages: list[str] | None = None, simplify: bool = False) -> None:
    """
    Merges multiple OWL/RDF files into a single one.
    """
    graph = create_graph()
    for input in inputs or [".ttl:-"]:
        rdf_read(graph, input)

    if languages:
        languages = {lang for lang_list in languages for lang in lang_list.split(",")}
        for triple in list(graph):
            o = triple[2]
            if isinstance(o, Literal) and o.language and o.language not in languages:
                graph.remove(triple)

    if simplify:
        graph.remove((None, OWL.imports, None))

    rdf_write(graph, output_file)


@_cli.command(name="split")
@click.argument("inputs", metavar="INPUT_FILE...", nargs=-1)
@click.option("-o", "--output-dir", default="./", help="directory where to create output files (default: working dir)")
@click.option("-l", "--leftover-file", help="RDF file where to save leftover triples (optional)")
def _cli_split(inputs: list[str], output_dir: str = "./", leftover_file: str | None = None) -> None:
    """
    Split merged RDF data about multiple ontologies into multiple output RDF files, one per ontology.

    Input data is read from specified input files (use '-' for stdin, prepend '.ext:' to force a different RDF format).
    Look for owl:Ontology IRIs in the input, read their annotations, and based on them emits a file for each ontology.
    """
    graph = create_graph()
    for input in inputs or [".ttl:-"]:
        rdf_read(graph, input)

    leftover = create_graph(namespaces_from=graph) if leftover_file else None

    modules = split(graph, leftover)

    for path_rel, graph_out in modules.items():
        path_abs = path.join(output_dir, path_rel)
        Path(path_abs).parent.mkdir(parents=True, exist_ok=True)
        rdf_write(graph_out, path_abs)

    if leftover is not None:
        rdf_write(leftover, leftover_file)



import xml.etree.ElementTree as ET
from xml.dom import minidom

@_cli.command(name="catalog")
@click.argument("inputs", metavar="INPUT_PATH...", nargs=-1)
@click.option("-o", "--output-file", default="-", help="output catalog file (e.g., catalog-v001.xml, use '-' for stdout, the default)")
def _cli_catalog(inputs: list[str], output_file: str = "-") -> None:
    """
    Generate catalog-v001.xml files for use in Protégé / OWL API.
    """
    paths = {Path(i) for i in inputs}
    dirs = {p for p in paths if p.is_dir()}
    files = {p for p in paths if p.is_file()} | {f for d in dirs for f in d.rglob('*') if guess_format(f.as_posix())}

    root = ET.Element("catalog", attrib={"prefer": "public", "xmlns": "urn:oasis:names:tc:entity:xmlns:xml:catalog"})

    for f in sorted(files):
        if str(f.parts[-1]) == 'catalog-v001.xml':
            continue
        graph = create_graph()
        graph.parse(source=f)
        iris = {iri for iri, _, _ in graph.triples((None, RDF.type, OWL.Ontology)) if isinstance(iri, URIRef)}
        if not iris:
            logging.warning(f"File '{f}' contains no owl:Ontology declaration: ignoring file")
        elif len(iris) == 1:
            iri = next(iter(iris))
            id = f.as_posix().rsplit("/", 1)[-1].split(".", 1)[0]
            ET.SubElement(root, "uri", attrib={"id": id, "name": str(iri), "uri": f.as_posix()})
        else:
            logging.warning(f"File '{f}' contains multiple owl:Ontology declarations: generating multiple catalog entries for the same file")
            id_base = f.as_posix().rsplit("/", 1)[-1].split(".", 1)[0]
            for idx, iri in enumerate(sorted(iris)):
                id = f"{id_base} ({idx + 1})"
                ET.SubElement(root, "uri", attrib={"id": id, "name": str(iri), "uri": f.as_posix()})

    with sys.stdout.buffer if output_file == "-" else open(output_file, "wb") as f:
        f.write(minidom.parseString(ET.tostring(root, 'utf-8', xml_declaration=True)).toprettyxml(indent="    ", encoding="utf-8"))


@_cli.command(name="mermaid")
@click.argument("inputs", metavar="INPUT_FILE...", nargs=-1)
@click.option("-o", "--output-file", default="-", help="output markdown file ('-' for stdout, the default)")
@click.option("-e", "--extra-content", multiple=True, help="optional additional Mermaid code to inject into the diagram")
def _cli_mermaid(inputs: list[str], output_file: str = "-", extra_content: tuple[str, ...] = ()) -> None:
    """
    Generates a Markdown + Mermaid diagram of ontology owl:imports / voaf:reliesOn relations.
    """
    graph = create_graph()
    for input in inputs or [".ttl:-"]:
        rdf_read(graph, input)

    diagram = mermaid(graph, extra_content)

    with sys.stdout if output_file == "-" else open(output_file, "wt") as f:
        f.write(diagram)


@_cli.command(name="ecv")
@click.argument("input", metavar="INPUT_FILE")
@click.option("-o", "--output-prefix", default="ecv", help="base name of generated files")
@click.option("-s", "--sql-prefix", default="", help="prefix of generated SQL tables (default: '')")
def _cli_ecv(input: str, output_prefix: str = "ecv", sql_prefix: str = "") -> None:

    def emit_csv(graph: Graph, output_file: str, query: str) -> None:
        results = graph.query(query)
        csv_content = results.serialize(format="csv")
        with open(output_file, "wb") as f:
            f.write(csv_content)

    graph = create_graph()
    rdf_read(graph, input)

    with open(output_prefix + ".sql", "wt") as f:
        f.write(dedent(ECV_SQL_TEMPLATE.substitute(tbl_prefix=sql_prefix)).lstrip())

    with open(output_prefix + ".obda", "wt") as f:
        f.write(dedent(ECV_OBDA_TEMPLATE.substitute(tbl_prefix=sql_prefix)).lstrip())

    emit_csv(graph, output_prefix + ".domain.csv", """
        SELECT ?id ?label {
            ?iri a ecv:ECV-domain ; rdfs:label ?label
            BIND(STRAFTER(STR(?iri), STR(ecv:)) AS ?id)
        } ORDER BY ?id
    """)

    emit_csv(graph, output_prefix + ".subdomain.csv", """
        SELECT ?id ?domain_id ?label {
            ?iri a ecv:ECV-subdomain ; skos:broader ?domain ; rdfs:label ?label
            BIND(STRAFTER(STR(?iri), STR(ecv:)) AS ?id)
            BIND(STRAFTER(STR(?domain), STR(ecv:)) AS ?domain_id)
        } ORDER BY ?id
    """)

    emit_csv(graph, output_prefix + ".variable.csv", """
        SELECT ?id ?subdomain_id ?label ?definition {
            ?iri a ecv:ECV-variable ; clex:isMemberOf ?subdomain ; rdfs:label ?label
            OPTIONAL { ?iri skos:definition ?definition }
            BIND(STRAFTER(STR(?iri), STR(ecv:)) AS ?id)
            BIND(STRAFTER(STR(?subdomain), STR(ecv:)) AS ?subdomain_id)
        } ORDER BY ?id
    """)

    emit_csv(graph, output_prefix + ".product.csv", """
        SELECT DISTINCT ?id ?label ?definition ?note ?unit_note {
            ?iri a ecv:ECV-product ; rdfs:label ?label ; skos:definition ?definition
            OPTIONAL { ?iri skos:note ?note FILTER(!STRSTARTS(?note, "Unit: ")) }
            OPTIONAL { ?iri skos:note ?n FILTER(STRSTARTS(?n, "Unit: ")) BIND(STRAFTER(?n, "Unit: ") AS ?unit_note)}
            BIND(STRAFTER(STR(?iri), STR(ecv:)) AS ?id)
        } ORDER BY ?id
    """)

    emit_csv(graph, output_prefix + ".product_variable.csv", """
        SELECT ?product_id ?variable_id {
            ?iri a ecv:ECV-product ; ecv:isProductOf ?variable
            BIND(STRAFTER(STR(?iri), STR(ecv:)) AS ?product_id)
            BIND(STRAFTER(STR(?variable), STR(ecv:)) AS ?variable_id)
        } ORDER BY ?product_id ?variable_id
    """)

    emit_csv(graph, output_prefix + ".product_unit.csv", """
        SELECT DISTINCT ?id ?unit_id ?unit_ns {
            ?iri a ecv:ECV-product ; qudt:hasUnit ?unit
            BIND(STRAFTER(STR(?iri), STR(ecv:)) AS ?id)
            BIND(REPLACE(REPLACE(REPLACE(STR(?unit), STR(cunit:), "cunit:"), STR(unit:), "unit:"), STR("wmdr-unit"), "wmdr-unit:") AS ?uqn)
            BIND(STRAFTER(?uqn, ":") AS ?unit_id)
            BIND(STRBEFORE(?uqn, ":") AS ?unit_ns)
        } ORDER BY ?id ?unit_id ?unit_ns
    """)


ECV_SQL_TEMPLATE = Template("""
    CREATE TABLE ${tbl_prefix}domain (
        id VARCHAR NOT NULL,
        label VARCHAR NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ${tbl_prefix}subdomain (
        id VARCHAR NOT NULL,
        domain_id VARCHAR NOT NULL,
        label VARCHAR NOT NULL,
        PRIMARY KEY (id),
        FOREIGN KEY (domain_id) REFERENCES ${tbl_prefix}domain(id)
    );

    CREATE TABLE ${tbl_prefix}variable (
        id VARCHAR NOT NULL,
        subdomain_id VARCHAR NOT NULL,
        label VARCHAR NOT NULL,
        definition VARCHAR,
        PRIMARY KEY (id),
        FOREIGN KEY (subdomain_id) REFERENCES ${tbl_prefix}subdomain(id)
    );

    CREATE TABLE ${tbl_prefix}product (
        id VARCHAR NOT NULL,
        label VARCHAR NOT NULL,
        definition VARCHAR,
        note VARCHAR,
        unit_note VARCHAR
        PRIMARY KEY (id)
    );

    CREATE TABLE ${tbl_prefix}product_unit (
        product_id VARCHAR NOT NULL,
        unit_id VARCHAR NOT NULL,
        unit_ns VARCHAR NOT NULL,
        PRIMARY KEY (product_id, unit_id, unit_ns),
        FOREIGN KEY (product_id) REFERENCES ${tbl_prefix}product(id)
    );

    CREATE TABLE ${tbl_prefix}product_variable (
        product_id VARCHAR NOT NULL,
        variable_id VARCHAR NOT NULL,
        PRIMARY KEY (product_id, variable_id),
        FOREIGN KEY (product_id) REFERENCES ${tbl_prefix}product(id)
    );
""")

ECV_OBDA_TEMPLATE = Template("""
    [PrefixDeclaration]
    rdfs:       http://www.w3.org/2000/01/rdf-schema#
    skos:       http://www.w3.org/2004/02/skos/core#
    qudt:       http://qudt.org/schema/qudt#
    ecv:        http://www.semanticweb.org/crima/crima-ecv#
    cunit:      http://www.semanticweb.org/crima/crima-unit#
    unit:       http://qudt.org/vocab/unit/
    wmdr-unit:  http://codes.wmo.int/wmdr/unit/

    [MappingDeclaration] @collection [[
    mappingId   ${tbl_prefix}domain
    target      ecv:{id} a ecv:ECV-domain ; rdfs:label "{label}"@en .
    source      SELECT * FROM ${tbl_prefix}domain

    mappingId   ${tbl_prefix}subdomain
    target      ecv:{id} a ecv:ECV-subdomain ; skos:broader ecv:{domain_id} ; rdfs:label "{label}"@en .
    source      SELECT * FROM ${tbl_prefix}subdomain

    mappingId   ${tbl_prefix}variable
    target      ecv:{id} a ecv:ECV-variable ; clex:isMemberOf ecv:{subdomain_id} ; rdfs:label "from string import Template{label}"@en ; skos:definition "{definition}"@en .
    source      SELECT * FROM ${tbl_prefix}variable

    mappingId   ${tbl_prefix}product
    target      ecv:{id} a ecv:ECV-product ; rdfs:label "{label}"@en ; skos:definition "{definition}"@en ; skos:note "{note}"@en , "{unit_note_lit}"@en .
    source      SELECT *, CONCAT('Unit: ', unit_note) AS unit_note_lit FROM ${tbl_prefix}product

    mappingId   ${tbl_prefix}product_variable
    target      ecv:{product_id} ecv:isProductOf ecv:{variable_id} .
    source      SELECT * FROM ${tbl_prefix}product_variable

    mappingId   ${tbl_prefix}product_unit_cunit
    target      ecv:{product_id} qudt:hasUnit cunit:{unit_id} .
    source      SELECT * FROM ${tbl_prefix}product_unit WHERE unit_ns = 'cunit'

    mappingId   ${tbl_prefix}product_unit_unit
    target      ecv:{product_id} qudt:hasUnit unit:{unit_id} .
    source      SELECT * FROM ${tbl_prefix}product_unit WHERE unit_ns = 'unit'

    mappingId   ${tbl_prefix}product_unit_wmdr_unit
    target      ecv:{product_id} qudt:hasUnit wmdr-unit:{unit_id} .
    source      SELECT * FROM ${tbl_prefix}product_unit WHERE unit_ns = 'wmdr-unit'
    ]]
""")


if __name__ == "__main__":
    _cli()
